### ISSUE TITLE
Color palette standard

### ISSUE THREAD

**Issue by lee2sman** [lee2sman/chirp#11]
Research trending colors or proceed and  be bold. Need a comprehensive color pallet. With those colors listed here so we know what to use.

**Comment by pderival823** [comment]
I’ll work on this

**Comment by lee2sman** [comment]
For example, check out [coolors.co](https://coolors.co). Make sure to also coordinate with #2 to make sure your palette is accessible

**Comment by pderival823** [comment]
Made some changes to the color scheme based on the palette discussed on discord. Open to any and all suggestions on color changes to make it look better. Tried to follow the color scheme of the logo the best i could but once again feel free to make any suggestions on improvements and/or changes.

**Comment by lee2sman** [comment]
Resolved in #28
